# Please don't edit this file, and use the version generated at
# http://rainboard.laas.fr/project/pinocchio/.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  CCACHE_BASEDIR: "${CI_PROJECT_DIR}"
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"

cache:
  paths:
    - ccache

.robotpkg-pinocchio: &robotpkg-pinocchio
  except:
    - gh-pages
  script:
    - mkdir -p ccache
    - cd /root/robotpkg/math
    - git pull
    - cd pinocchio
    - make checkout MASTER_REPOSITORY="dir ${CI_PROJECT_DIR}"
    - make install
    - cd work.$(hostname)/$(make show-var VARNAME=DISTNAME)
    - git rev-parse --show-toplevel
    - git describe --tags
    - make test

robotpkg-pinocchio-16.04-release:
  <<: *robotpkg-pinocchio
  image: eur0c.laas.fr:5000/stack-of-tasks/pinocchio/pinocchio:16.04
