name: Test Pinocchio on Linux

on: [push,pull_request]

env:
  CC: clang
  CXX: clang++
  CMAKE_PREFIX_PATH: /opt/openrobots
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - run: |
        PY_MIN=$(python3 -V 2>&1 | cut -d. -f2)
        sudo sh -c "echo '/opt/openrobots/lib/python3.$PY_MIN/site-packages' >> /usr/lib/python3/dist-packages/robotpkg.pth"
        DEB="deb [arch=amd64] http://robotpkg.openrobots.org"
        sudo sh -c "echo '$DEB/wip/packages/debian/pub $(lsb_release -cs) robotpkg' >> /etc/apt/sources.list"
        sudo sh -c "echo '$DEB/packages/debian/pub $(lsb_release -cs) robotpkg' >> /etc/apt/sources.list"
        sudo apt-key adv --fetch-keys http://robotpkg.openrobots.org/packages/debian/robotpkg.key
        sudo apt-get update -qq
        sudo apt-get install -qqy clang cmake lib{urdfdom,tinyxml}-dev robotpkg-py3$PY_MIN-{casadi,hpp-fcl}

    - run: |
        rm -rf build
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_WITH_COLLISION_SUPPORT=ON -DBUILD_ADVANCED_TESTING=ON \
              -DBUILD_WITH_CASADI_SUPPORT=ON -DPYTHON_EXECUTABLE=$(which python3) -DBUILD_WITH_OPENMP_SUPPORT=ON ..
        make
        make build_tests
        make test
        sudo make install
